### ISSUE TITLE
[BUG] Types/defaults generate HTML <code> instead of MD backticks

### ISSUE THREAD

**Issue by alystair** [jsdoc2md/jsdoc-to-markdown#239] opened 2021-04-02 00:22 UTC
Return type, properties etc... all become `<code>` HTML tags instead of conventional markdown \` backticks

```js
/** Register a function that executes when the `triggers` parameter passes the destination object's `HOOK.exec` filter.
 * @param {Object} dstObj Destination object. If no `hooks` array property exists within, it is created.
 * @param {(Array.<string>|string)} triggers Array of strings, or a string which is split by spaces and converted into an array. Used by hook execution filter.
 * @param {!function} fn Executed when triggers pass the `dstObj` trigger filter
 * @param {Number} [priority] Execution index, negative integers are added from the end of the list
 * @returns {Number} Hook ID (execution order) */
```
generates

```md
### HOOK.add(dstObj, triggers, fn, [priority]) ⇒ <code>Number</code>
Register a function that executes when the `triggers` parameter passes the destination object's `HOOK.exec` filter.

**Kind**: static method of [<code>HOOK</code>](#pd.HOOK)  
**Returns**: <code>Number</code> - Hook ID (execution order) 

| Param | Type | Description |
| --- | --- | --- |
| dstObj | <code>Object</code> | Destination object. If no `hooks` array property exists within, it is created. |
| triggers | <code>Array.&lt;string&gt;</code> \| <code>string</code> | Array of strings, or a string which is split by spaces and converted into an array. Used by hook execution filter. |
| fn | <code>function</code> | Executed when triggers pass the `dstObj` trigger filter |
| [priority] | <code>Number</code> | Execution index, negative integers are added from the end of the list |
```

**Comment by 75lb** [comment] 2021-04-07 08:57
Hi, `<code>` is used by design - backticks were used originally but we switched to using `<code>` for greater markdown parser compatibility (some parsers failed to render backtick expressions containing new lines, hyperlinks etc).. 

Is there a pressing reason you must use backticks instead of `<code>`?

**Comment by 75lb** [comment] 2021-04-07 13:16
closing as `<code>` is used by design

**Closed by 75lb** 2021-04-07 13:16 UTC
Labels: wontfix

**Comment by alystair** [comment] 2021-04-07 14:11
Because:
- Markdown should be consistent and human readable.
- Project is named jsdoc2md, not jsdoc2html.
- It's not your fault some renderers cannot follow spec.

I understand if you need this as a default for improving renderer compatibility - but at least give the option for behaving renderers - or tell me how to change this behavior myself.

Why leave issue /wo response for 6 days then give 4hrs for feedback before closing issue? Not everyone has same working hours (was sleeping)

**Comment by 75lb** [comment] 2021-04-07 14:19
I understand, however re-implementing backticks would be a breaking change so I need a solid reason to do it, as it affects users of alternative markdown engines..

**Comment by alystair** [comment] 2021-04-07 14:24
Thanks for the immediate response. If you could hint where in the code base this happens I could take a look as well.

If this behavior is placed behind a flag/option it would not to be a breaking change.

**Comment by 75lb** [comment] 2021-04-07 14:29
there are a few partials that use `<code>`
https://github.com/jsdoc2md/dmd/search?l=Handlebars&q=%3Ccode%3E
