### ISSUE TITLE
Colons instead of arrows? Or no return value in header?

### ISSUE THREAD

**Issue by jtlapp** [jsdoc2md/jsdoc-to-markdown#93] opened 2016-09-10 05:39 UTC
Is there an option for displaying the return values of functions with a colon instead of an arrow? Or for not showing the return value in the header?

I've been programming since 1982. I spent 5 seconds staring at the example headers output for function calls wondering what the heck the arrow notation meant. I figured it out of course, but I find the whole presentation unusual, awkward, and distracting.

I'd like to generate markdown that provides an intuitive presentation. I'd be happy to even just show the return value in the text under the header and not in the header itself. That leaves more room for parameters anyway.

I also find it distracting that the return value appears more emphasized than the function itself. If anything were emphasized, I'd prefer it to be the function name.

Thanks for your help.

**Comment by 75lb** [comment] 2016-09-10 10:30
hi! I've been programming since '85, so from a similar era.. yes, you can customise the output - take a look at the [docs for dmd](https://github.com/jsdoc2md/dmd) which talk about how to override handlebars partials, helpers and build plugins (if required). 

In your case (modifying the signature), you would create a duplicate of one/all of the [signature partials](https://github.com/jsdoc2md/dmd/tree/master/partials/shared/signature) in your project, modify them, then pass their filepaths as args to jsdoc2md, (the partial filenames are significant, so must remain the same as their original name) e.g. 

```
$ jsdoc2md --partial sig-name.hbs sig-link.hbs
```

**Comment by 75lb** [comment] 2016-09-10 10:56
any other questions, let me know - here or in the gitter room.. unfortunately, Handlebars was not the best choice so the templates are difficult to read and understand.. this will be fixed in a future version (i.e. rewritten)

**Closed by 75lb** 2016-09-10 10:56 UTC
Labels: question

**Comment by jtlapp** [comment] 2016-09-10 13:57
Perfect response. Thank you!

TRS-80, Commodore, or Atari? I started with an Atari 400, but all the cool kids were using TRS-80.

**Comment by jtlapp** [comment] 2016-09-10 17:02
The more I play with these tools, the more awesome they get. Well done! You've thought of everything and made it pretty easy too. (But yeah, the hbs is a bit hard to read.)
