### ISSUE TITLE
@external does not get output

### ISSUE THREAD

**Issue by liabru** [jsdoc2md/jsdoc-to-markdown#99] opened 2016-10-23 18:21 UTC
Using `@external` does not seem to be showing up in the output when using `jsdoc2md` CLI where as it does using `jsdoc` CLI.

```js
/**
 * @module MatterAttractors
 */

/**
 * @external "Matter.Body"
 * @see {@link http://brm.io/matter-js/docs/classes/Body.html}
 */
```

When I run `jsdoc2md *.js > API.md` I get the output:

```md
<a name="module_MatterAttractors"></a>

## MatterAttractors
```

Where the externals are missing. Where as if I run `jsdoc *.js` and open the resulting html output I can see:

```
Modules
MatterAttractors

Externals
Matter.Body
```

I'm using `"jsdoc-to-markdown": "^2.0.1"`.  The [wiki](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Linking-to-external-resources) seems to suggest this should be supported?

I've tried various other combinations of using `external:` paths and using `@name`. Sometimes they show up, but always as `*Kind**: inner class of <code>[MatterAttractors](#module_MatterAttractors)</code>` which is wrong. I also tried using `@memberof`, but this always causes the block to never show up (another bug maybe).

Thanks!

**Comment by 75lb** [comment] 2016-10-23 18:47
hi! This is my fault, my docs are missing some crucial information. 

The short answer:`@external` tags without descriptions are not rendered. If you add a description it will appear in output, e.g.:

```
/**
 * An external reference. 
 * @external "Matter.Body"
 * @see {@link http://brm.io/matter-js/docs/classes/Body.html}
 */
```

The `@external` tag style you wrote (no description and a `@see`) triggered some magic (described in the wiki). Internally, this maps the namepath `external:Matter.Body` to the url http://brm.io/matter-js/docs/classes/Body.html.

```
/**
 * @external "Matter.Body"
 * @see {@link http://brm.io/matter-js/docs/classes/Body.html}
 */
```

So, if you were to reference this external's namepath somewhere in the docs (example below), the jsdoc2md output would automatically link to the url defined by your `@see` tag for the external `Matter.Body`. 

```
/**
 * @type {external:Matter.Body}
 */
var matterBody = null
```

Incidentally, to list all valid namepaths in your project, run:

```
$ jsdoc2md --namepaths lib/*.js
```

Does that help?

**Comment by 75lb** [comment] 2016-10-24 06:58
closing, as this is the expected behaviour.. happy to continue the discussion, though.

**Closed by 75lb** 2016-10-24 06:58 UTC

**Comment by liabru** [comment] 2016-10-24 09:03
After adding the description it shows up, so that seems to work thanks. Is it the case then that everything needs a description?

**Comment by 75lb** [comment] 2016-10-24 09:17
no, it is only the case with `@external` because most users only want the [link to external resource](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Linking-to-external-resources) feature you get by combining `@external` with `@see`. So, if the user didn't provide a description for the `@external` it is assumed they only wanted the link and that there is no requirement to render the un-described external in the output.

**Comment by liabru** [comment] 2016-10-24 10:23
Ah ok, so I'd need to reference it somewhere before I'd see it in that case. Thanks for the help.
