### ISSUE TITLE
 Cannot find module 'collect-all' issue

### ISSUE THREAD

**Issue by jkrls84** [jsdoc2md/jsdoc-to-markdown#237] opened 2021-03-25 11:11 UTC
Hello!!

I'm trying tu use 7.0.0 version, running the script:

```
jsdoc2md -f *.js -f **/*.js > docs/API.md
```

And we catch the next error :

```
Error: Cannot find module 'collect-all'
Require stack:
- ...\node_modules\jsdoc-api\lib\explain.js
- ...\node_modules\jsdoc-api\index.js
- ...\node_modules\jsdoc-to-markdown\index.js
-  ...\node_modules\jsdoc-to-markdown\bin\cli.js
```

how we can run jsdocs over all `*/*.js` files in project?

Thanks for all.

**Comment by 75lb** [comment] 2021-03-25 11:16
which operating system are you using?

**Comment by 75lb** [comment] 2021-03-25 11:20
also, which version of node and npm? I can't reproduce this..

**Comment by 75lb** [comment] 2021-03-25 11:26
I refreshed the dependencies and published v7.0.1 of jsdoc2md.. please completely remove your current version and try the new version..

**Comment by jkrls84** [comment] 2021-03-26 07:21
Hello,

I'm using Windows 10
npm: 6.14.11
node: 14.16.0

I already did, delete node modules and re-download all dependencies. jsdoc-to-markdown is version 7.0.0

**Comment by jkrls84** [comment] 2021-03-26 07:24
I have all dependencies updated

**Comment by 75lb** [comment] 2021-03-26 11:35
I still can't reproduce this - I am trying on Windows with node v15.. I installed `jsdocmd` globally and ran many different commands without error.. Please post a link to a dummy project or gist that I can download, run and see fail.. cheers.

**Comment by 75lb** [comment] 2021-05-16 10:21
closing until I receive more info.

**Closed by 75lb** 2021-05-16 10:21 UTC
Labels: more info
