### ISSUE TITLE
Issue where param has _ renders doc as italic

### ISSUE THREAD

**Issue by reggi** [jsdoc2md/jsdoc-to-markdown#39] opened 2015-07-29 21:19 UTC

**Comment by 75lb** [comment] 2015-12-09 11:48
i can't reproduce this, can you send me a failing example please?

**Comment by 75lb** [comment] 2015-12-09 11:49
also, let me know *where* you see it failing.. github, npm, something else?

**Comment by reggi** [comment] 2015-12-09 16:08
The idea here would be to replace underscores with the HTML entity `&#95;` because some markdown parsers see the `_` and think italic and want to italic all that comes after, github's parser is a little smarter as shown [here](https://gist.github.com/reggi/7591dcc5fd1b4d5b5e65).

```js
/**
a quite wonderful function
@param {object} - cloak
@param {object} - security
@returns {survival}
*/
function protection(_cloak, dagger){}
```

However as you can see here, atom's is not.

![screen shot 2015-12-09 at 11 05 51 am](https://cloud.githubusercontent.com/assets/296798/11690544/340fe24e-9e65-11e5-86aa-4f00f8e292a6.png)

**Comment by 75lb** [comment] 2015-12-09 16:49
which version of Atom is that? I can't reproduce it in Atom Stable or Beta.. 

![screen shot 2015-12-09 at 16 47 01](https://cloud.githubusercontent.com/assets/1247980/11691805/9baec580-9e94-11e5-98af-f3e62e713dde.png)

Closing as the current output is valid markdown.

**Closed by 75lb** 2015-12-09 16:49 UTC
