### ISSUE TITLE
@file overview comment not rendering

### ISSUE THREAD

**Issue by mysticaltech** [jsdoc2md/jsdoc-to-markdown#219] opened 2020-07-23 10:45 UTC
Hey folks, I have the following at the beginning of my source and I would expect it to render (it does with normal jsdoc) but it does not with jsdoc2md. Any ideas of how to make this render? Everything else renders but the first block with **@file**!
```
/**
 * @file The XYZ Library main file
 * @author Karim <karim@mysticaltech.com>
 * @copyright XYZ, inc
 * @version 0.1.0-alpha
 */

/**
 * Metrics string values
 * @enum {string}
 */
/** x value */
const metricsEnum = {
  x: 'x',
  /** y value */
  y: 'y',
}

```

**Comment by 75lb** [comment] 2021-03-25 13:57
duplicate of https://github.com/jsdoc2md/jsdoc-to-markdown/issues/84

**Closed by 75lb** 2021-03-25 13:57 UTC
