### ISSUE TITLE
{{>member-index~}} does not produce a member index if module has only one member

### ISSUE THREAD

**Issue by tnunes** [jsdoc2md/jsdoc-to-markdown#34] opened 2015-05-28 19:51 UTC
Using the following template in a `.hbs` file, `jsdoc-to-markdown` does not produce a listing with one member for the index of modules containing one single member:

```
# Index

{{#modules~}}
  ## {{name}}
  > {{>body}}
  {{>member-index~}}
{{/modules}}

# Modules and methods

{{#modules~}}
  ## &nbsp;&nbsp;{{name}}
  > {{>body~}}
  {{>members~}}
{{/modules}}
```

Am I missing something or is this indeed a bug?

**Comment by 75lb** [comment] 2015-05-28 20:05
which version are you running? the latest release (1.1.1) or something else?

**Comment by tnunes** [comment] 2015-05-29 22:23
Yes, I'm running 1.1.1.

**Comment by 75lb** [comment] 2015-05-29 22:25
that's odd, i couldn't reproduce this using v1.1.1.. it worked fine for me using your template.. could you send a link to your repo, or to a gist containing the module that is failing please

**Comment by tnunes** [comment] 2015-05-29 22:57
A simple module like this should be enough to reproduce the bug:

```js
/**
 * @module test
 * @desc This is a simple module to show a bug in jsdoc-to-markdown
 */

/**
 * Decription of this simple method
 *
 * @param  {String}   firstParam  The first param
 * @param  {String}   secondParam  The second param
 * @return {Object}  <code><pre>
 *     {
 *       sampleValue: '',
 *       anotherValue: '' 
 *     }
 * </pre></code>
 */
exports.myTestMethod = function (firstParam, secondParam) {
  // Some code here
}
```

**Comment by 75lb** [comment] 2015-05-30 21:12
i can't reproduce your issue, it works fine for me with your exact code and template.. try uninstalling then reinstalling the tool/plugin.. which version of node and npm are you running? 

see this gist.. you can see from the file `output.md` that it works.. install it yourself then run `npm run docs` in the root directory. 
https://gist.github.com/75lb/ffff278900178e344bcd

**Comment by tnunes** [comment] 2015-06-02 10:15
Actually your gist reproduces my issue. See what happens when I add another method: https://gist.github.com/tnunes/3807358cf0e47126c636

That `{{>member-index~}}` tag is not producing any output in the first case, with only one method, whereas in the second, with two methods, it produces a listing of the module contents.

**Comment by tnunes** [comment] 2015-06-15 11:31
Any update on this issue?

**Comment by 75lb** [comment] 2015-06-16 08:00
> That {{>member-index~}} tag is not producing any output in the first case, with only one method, whereas in the second, with two methods, it produces a listing of the module contents.

that is the desired behaviour, see [here](https://github.com/jsdoc2md/dmd/blob/v1.1.1/partials/all-docs/docs/member-index/member-index.hbs#L1). The member-index is only displayed if the object has minimum 2 members.. A member index containing just a single member is not worth displaying. What's the point having a "table of contents" if it only one entry, pointing to page 1?

**Comment by tnunes** [comment] 2015-06-16 10:11
I believe that choice should be left to users. If I don't want to display a table of contents because a module only has one member, I will omit the `{{>member-index~}}` tag. If I include it explicitly I expect the tool I'm using to include one.

I'm building documentation for quite a few services using consistent templates. Most services have several members, but I just came across one that exports one module with just one member. That part of the documentation then becomes inconsistent with the rest, since that single module does not have an index (with one member, yes :)).

If you remove that constraint, users can opt to produce or not indexes for modules with one member, but like it is now, it is effectively impossible to do it, if one wants to. Would you consider removing that limitation or providing an option to override it?

**Comment by 75lb** [comment] 2015-06-16 10:12
no problem, i will make it a config option.. leaving this issue open until it's done. 

cheers :+1:

**Comment by tnunes** [comment] 2015-06-16 10:15
Thanks! :+1:

Cheers

**Comment by joanamelo** [comment] 2015-09-09 14:52
Happening to me as well! On v1.1.1. Would be much appreciated :)

My view: The index of available methods on a module should always be presented (imagine a book with many chapters. One of them only has one subchapter — that will be missing from the index!).

**Comment by tnunes** [comment] 2015-09-11 09:50
Hi @75lb. Any updates on this issue?

**Comment by 75lb** [comment] 2015-09-11 09:52
Hi Tiago, i'm sorry - no update yet.. I'm not sure when it will be fixed as i have so much happening at the moment.. sorry.. PRs welcome..

**Closed** 2015-12-09 14:38 UTC
Labels: enhancement

**Comment by 75lb** [comment] 2015-12-09 15:50
Fixed in the latest version. You need to set your preferred "minimum descendants" value in your project config. 

In the projects which require this setting, you can either add `dmd` config to your package.json:
```
"name": "whatever", 
"version": "1.0.0",
...
"dmd": {
  "memberIndex": {
    "minDescendants": 1
  }
}
```

or create a separate file called `.dmd.json` in the project root, with this content: 
```
"memberIndex": {
  "minDescendants": 1
}
```

**Comment by tnunes** [comment] 2015-12-14 17:48
Thanks for this! Best.

**Comment by 75lb** [comment] 2020-06-14 13:41
***Updated solution if you hit this issue***

By default, a minimum of 2 members is required for a member-index to print.

To change the minimum to 1, create a file called `.jsdoc2md.json` in your project folder with this content: 

```
{
  "memberIndex": {
    "minDescendants": 1
  }
}
```

Then generate the docs again.
