### ISSUE TITLE
Class is not documented correctly when it comes after the import statement

### ISSUE THREAD

**Issue by dragonza** [jsdoc2md/jsdoc-to-markdown#211] opened 2020-03-30 22:36 UTC
I have a file `Foo.js` which looks like this
```
/**
 * @module moduleName
 */

import {escape, unescape} from 'querystring'

/**
 * something here
 */
export class Foo {
    
}
```
I ran `jsdoc2md ./Foo.js`, it did not generate any output for the class. If I removed the `import` line, then it worked as expected. 

I need some advice on this matter. Thanks in advance

**Comment by 75lb** [comment] 2020-03-31 08:53
I pasted your example code into a file. I get the same jsdoc2md output (below) whether the `import` statement is present or not. The output for the class is present in both cases.

```md
<a name="module_moduleName"></a>

## moduleName
<a name="module_moduleName.Foo"></a>

### moduleName.Foo
something here

**Kind**: static class of [<code>moduleName</code>](#module_moduleName)  
```

I can't reproduce your issue. Please show me your output..

**Comment by dragonza** [comment] 2020-03-31 17:28
I think I found the issue on jsdoc. Please see https://github.com/jsdoc/jsdoc/issues/1718. My project is omitting the semicolon after the statement. If there is no valid code between the import and export, the document will be ignored. I am putting a workaround suggested in the thread since there is no solution yet. 

Thanks for your answer!

**Comment by 75lb** [comment] 2020-03-31 18:32
Oh, it's related to the jsdoc semicolon bug! At least there is a workaround.. will close this.

**Closed by 75lb** 2020-03-31 18:32 UTC
