### ISSUE TITLE
enum not being added to doc

### ISSUE THREAD

**Issue by g-ortuno** [jsdoc2md/jsdoc-to-markdown#53] opened 2015-10-16 23:10 UTC
I recently did `npm install` on a repo and now `enum`s are not being added to the doc. There were no changes in my code:

https://travis-ci.org/g-ortuno/eddystone#L505

**Comment by 75lb** [comment] 2015-10-17 13:07
[this project](https://github.com/75lb/ansi-escape-sequences) makes use of @enum - i just regenerated the docs and everything works fine.. i can't reproduce your issue.. 

please send a failing code example.. also, which version of node do you have? and which OS?

**Comment by g-ortuno** [comment] 2015-10-18 01:57
I was able to reproduce. Not sure if I miss something obvious, but whenever the docs are inside an function or arrow function nothing gets generated. This repo has the code:

https://github.com/g-ortuno/jsdoc-in-function

**Comment by g-ortuno** [comment] 2015-10-18 02:04
I use OSX and node 4.2.1

**Comment by 75lb** [comment] 2015-10-18 10:19
ok.. thanks for the extra info.. this is a known jsdoc issue with Immediate Invoked Function Expressions (IIFE).. if you look at the jsdoc-parse output (below), it shows the const `EddystoneFrameType` is a `"memberof": "<anonymous>"`.. however, a parent with the ID of `<anonymous>` does not exist in the data, so its children (your const) are never displayed.. 

will look into it, thanks for the report. 

```
$ jsdoc-parse arrow.js
[
  {
    "id": "<anonymous>~EddystoneFrameType",
    "longname": "<anonymous>~EddystoneFrameType",
    "name": "EddystoneFrameType",
    "scope": "inner",
    "kind": "constant",
    "description": "Possible Eddystone frame types.",
    "memberof": "<anonymous>",
    "type": {
      "names": [
        "string"
      ]
    },
    "readonly": true,
    "isEnum": true,
    "properties": [
      {
        "name": "URL",
        "longname": "<anonymous>~EddystoneFrameType.URL",
        "kind": "member",
        "memberof": "<anonymous>~EddystoneFrameType",
        "scope": "static",
        "type": {
          "names": [
            "string"
          ]
        },
        "defaultvalue": "url",
        "codeName": "URL"
      },
      {
        "name": "UID",
        "longname": "<anonymous>~EddystoneFrameType.UID",
        "kind": "member",
        "memberof": "<anonymous>~EddystoneFrameType",
        "scope": "static",
        "type": {
          "names": [
            "string"
          ]
        },
        "defaultvalue": "uid",
        "codeName": "UID"
      },
      {
        "name": "TLM",
        "longname": "<anonymous>~EddystoneFrameType.TLM",
        "kind": "member",
        "memberof": "<anonymous>~EddystoneFrameType",
        "scope": "static",
        "type": {
          "names": [
            "string"
          ]
        },
        "defaultvalue": "tlm",
        "codeName": "TLM"
      }
    ],
    "see": [
      "{@link https://github.com/google/eddystone/blob/master/protocol-specification.md|Protocol Specification}",
      "{@link https://github.com/google/eddystone/tree/master/eddystone-url|Eddystone-URL}",
      "{@link https://github.com/google/eddystone/tree/master/eddystone-uid|Eddystone-UID}",
      "{@link https://github.com/google/eddystone/tree/master/eddystone-tlm|Eddystone-TLM}"
    ],
    "order": 0
  }
]
```

**Comment by 75lb** [comment] 2015-10-18 10:20
duplicate of #29

**Comment by 75lb** [comment] 2015-10-18 11:08
the change in your output you saw recently was probably because i released a change introducing arrow function support..

**Comment by g-ortuno** [comment] 2015-10-18 18:14
thanks!

**Closed** 2015-12-05 15:30 UTC
Labels: bug, duplicate
